sonar.projectKey=opensophy-projects_docs
sonar.organization=opensophy-projects

sonar.sources=apps/web/src

sonar.exclusions=**/node_modules/**,**/build/**,**/.svelte-kit/**,apps/web/src/lib/content/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=apps/web/tsconfig.json
